### ISSUE TITLE
issue with sliding time window 

### ISSUE THREAD

**Issue by Ana-KG** [wmvanvliet/mne-rsa#11]
Hi, I think I found a small bug when trying to run "sliding time-window" style RSA with spatial_radius=None. 

**Error:**

  File "/opt/anaconda3/lib/python3.6/site-packages/mne/evoked.py", line 705, in __init__
    raise ValueError('Data must be a 2D array of shape (n_channels, '

ValueError: Data must be a 2D array of shape (n_channels, n_samples)

**Cause:**

This is caused by the fact that mne.EvokedArray expects (chan x times) array and lets (time, n)

**Fix:** 
Just making it  a 1 x list here fixes it:

    if spatial_radius is not None:
        info = epochs.info
        info = mne.pick_info(info, picks)
    else:
        info = mne.create_info(['rsa'], epochs.info['sfreq'])
        **data=[data]**#!!! Here

**Comment by wmvanvliet** [comment]
Fixed in #19

Thanks @Ana-KG for the debugging! Sorry I didn't get to it sooner.
