### ISSUE TITLE
ModuleNotFoundError: No module named 'mne_rsa'

### ISSUE THREAD

**Issue by Zhouyu0206** [wmvanvliet/mne-rsa#12]
Hi! I'm so exciting to found this wonderful package, but after I installed mne-rsa via "pip install mne-rsa", it showed that
Requirement already satisfied: mne-rsa in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (0.4)
Requirement already satisfied: matplotlib in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from mne-rsa) (3.3.2)
Requirement already satisfied: mne in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from mne-rsa) (0.22.dev0)
Requirement already satisfied: numpy in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from mne-rsa) (1.19.4)
Requirement already satisfied: scipy in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from mne-rsa) (1.5.2)
Requirement already satisfied: cycler>=0.10 in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from matplotlib->mne-rsa) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from matplotlib->mne-rsa) (8.0.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from matplotlib->mne-rsa) (2.8.1)
Requirement already satisfied: certifi>=2020.06.20 in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from matplotlib->mne-rsa) (2020.12.5)
Requirement already satisfied: numpy in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from mne-rsa) (1.19.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from matplotlib->mne-rsa) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from matplotlib->mne-rsa) (1.3.0)
Requirement already satisfied: six in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from cycler>=0.10->matplotlib->mne-rsa) (1.15.0)
Requirement already satisfied: scipy in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from mne-rsa) (1.5.2)
Requirement already satisfied: numpy in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from mne-rsa) (1.19.4)
Requirement already satisfied: six in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from cycler>=0.10->matplotlib->mne-rsa) (1.15.0)
Requirement already satisfied: numpy in c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\envs\mne\lib\site-packages (from mne-rsa) (1.19.4)
But, I cannot import this package no matter I typied "import rsa" or import "import mne_rsa", there always was prompt showing that ModuleNotFoundError: No module named 'rsa' or ModuleNotFoundError: No module named 'mne_rsa'. But when I install other packages like mne-bids or picard, it worked fine. 
Could you please tell me what can I do to solve this problem? I appreciate very much! Thank you!

**Comment by wmvanvliet** [comment]
Sorry about ignoring this for so long. Did you manage to fix it?

**Comment by wmvanvliet** [comment]
Since this is likely related to the user's Python installation and not MNE-RSA specific, I'm closing this issue for now. If you think this problem is in fact specific to MNE-RSA I'd be happy to re-open and discuss further.
