### ISSUE TITLE
Doesn't build on Windows

### ISSUE THREAD

**Issue by hoechenberger** [wmvanvliet/mne-rsa#16]
`setup.py` doesn't run on Windows:

```python
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\bld\mne-rsa_1646066101996\work\setup.py", line 21, in <module>
      long_description = fid.read()
    File "C:\bld\mne-rsa_1646066101996\_h_env\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 704: character maps to <undefined>
```

The reason is that you don't specify an encoding when loading `README.rst`, so Windows defaults to `cp1252`:

https://github.com/wmvanvliet/mne-rsa/blob/d375f21c97269846807314bf6d4538be72dbbf7f/setup.py#L20-L21

**Comment by hoechenberger** [comment]
I think this has been resolved. If you have time, could you make a new release with this fix, @wmvanvliet?

**Comment by wmvanvliet** [comment]
There are more fixes that need done. But once those are in, yes :)

**Comment by wmvanvliet** [comment]
Release done!
