### ISSUE TITLE
AttributeError: Can't pickle local object 'rsa.array.<locals>.call_rsa'

### ISSUE THREAD

**Issue by Ana-KG** [wmvanvliet/mne-rsa#2]
Hi, thanks for a nice implementation of rsa in mnepython.
I gotAttributeError: Can't pickle local object 'rsa.array.<locals>.call_rsa' when running sensor level searchlight. Im trying to figure out if this is my pickle version problem or something else

**Comment by wmvanvliet** [comment]
Hi! Thanks for bringing this to my attention. Today, I've merged in some major updates to the package. The biggest being I've renamed the package from `rsa` to `mne_rsa` to avoid a name clas with another package called `rsa`. Could you re-try on the latest version (0.4.dev0) and see if the error persists?

**Comment by Ana-KG** [comment]
Hi again, 
Thanks, I tried using the latest version with mne_rsa instead of rsa and it persists with identical error (Can't pickle local object 'rsa_array.<locals>.call_rsa') which originates in the the parallel processing. When go into the code and manually bypass the parallelisation it works (same was true for previous version)

**Comment by wmvanvliet** [comment]
The pickling is performed by the 'cloudpickle' package (called from the joblib package). The code is trying to pickle a python generator, which is something only recent versions of cloudpickle support. Could you try upgrading cloudpickle to the latest and greatest version?

**Comment by wmvanvliet** [comment]
Is this still an issue?

**Comment by Ana-KG** [comment]
Hi, sorry for a late reply! I have asked for that package to be updated on the server im working on as im not admin. Will test again when that happens.

**Comment by Ana-KG** [comment]
Finally, tested- It worked with the latest  'cloudpickle'  :)  Cheers!
