### ISSUE TITLE
Info (62) and data (1) must have same number of channels.

### ISSUE THREAD

**Issue by finch-f** [wmvanvliet/mne-rsa#27]
I planned to compute RSA in a searchlight pattern on evokeds with the function **rsa_evokeds**

So I have a list of evoked object for each item. Data of each evoked object is an array of 62 channels * 450 timepoints. Since I have 120 items in my data, the length of the evoked list is 120. And I have a model DSM of 120*120.

However, when performing RSA, I got an error: 

_'ValueError: Info (62) and data (1) must have same number of channels.'_

This is my script:

######################################################################################################
  epochlist = []
  
  subs = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
  
  for j in subs:
          
      sub_epoch = all_epochs[j-1].copy()
      
      epochlist.append(sub_epoch)
  
  epoch_concat = mne.concatenate_epochs(epochlist)
  
  evoked_list = []
  
  for n in items['itemid_s']:
      
      item_epoch = epoch_concat[epoch_concat.metadata['itemid']==n]
      
      item_evoke = item_epoch.average()
      
      evoked_list.append(item_evoke)
  
  rsa_result = rsa.rsa_evokeds(
      evoked_list,                         
      phonology_dist[np.triu_indices(120,k=1)],      
      evoked_dsm_metric='sqeuclidean', 
      rsa_metric='kendall-tau-a',       
      spatial_radius=0.45,           
      temporal_radius=0.02,       
      tmin=0.15, tmax=0.25,    
      n_jobs=3,                     
      n_folds=None,          
      verbose=False) 

######################################################################################################

Could you help me on this error? Many thanks~

![image](https://user-images.githubusercontent.com/39895713/217993655-56541fb0-d7e3-477a-a401-3e6e762b9737.png)

**Comment by finch-f** [comment]
I comment out the returning part of the script of function of rsa_evokeds:

![image](https://user-images.githubusercontent.com/39895713/218004677-02c3f0f4-8748-49aa-a02a-f3355fd80482.png)

This makes the rsa_evokeds function works, but return an rsa array of 62 sensors * 50 timepoints

And then I added the following scripts:

picks = mne.io.pick._picks_to_idx(evokelist[0].info, picks='all', none='data')

info = mne.pick_info(evokelist[0].info, picks)

X=mne.EvokedArray(np.atleast_2d(rsa_result), info, 0.15,
                               comment='RSA', nave=len(evokelist))
X.plot_topomap(X.times, units=dict(eeg='kendall-tau-a'),
                        scalings=dict(eeg=1), cbar_fmt='%.4f', nrows=5,
                        sphere=1)

This output the plots I want. 

Still do not know why the error is produced. Hope these changes could provide some clues.

**Comment by wmvanvliet** [comment]
This should be fixed now in version 0.10.
