### ISSUE TITLE
not using noise_cov for mne_rsa.rsa_epochs

### ISSUE THREAD

**Issue by weiyongxu** [wmvanvliet/mne-rsa#28]
Hi,
I am wondering why the noise normalization for the epoch data is commented out as in: 
https://github.com/wmvanvliet/mne-rsa/blob/e688f64f6e82fab0f7ed89e5fad7c26ccd141e7b/mne_rsa/sensor_level.py#L365

Weiyong

**Comment by wmvanvliet** [comment]
This has been fixed as of version 0.10!
