### ISSUE TITLE
ValueError: Info (61) and data (1) must have same number of channels.   

### ISSUE THREAD

**Issue by guishuyunye-lyw** [wmvanvliet/mne-rsa#30]
rsa_result = mne_rsa.rsa_evokeds(
    list_evoked,                         
    dsm_model=RDM_model_fuyin_xw_1d,                    
    rsa_metric='spearman',
    spatial_radius= 0.04,          
    temporal_radius=0.05,            
    tmin=0.4, tmax=0.5,           
    n_jobs=6,                      
    n_folds=None,                 
    verbose=True)

when I run the code, I got this error: 
ValueError: Info (61) and data (1) must have same number of channels. 

I debug the function and find out there maybe a mistake in the source code of .rsa_evokeds:
```

    if one_model:
        return mne.EvokedArray(np.atleast_2d(data[..., 0]), info, tmin,
                               comment='RSA', nave=len(evokeds))
```
I think it should be like: 

```

    if one_model:
        return mne.EvokedArray(np.atleast_2d(data), info, tmin,
                               comment='RSA', nave=len(evokeds))
```

**Comment by wmvanvliet** [comment]
You were absolutely right. Thanks for debugging this. Fixed in version 0.10.
