### ISSUE TITLE
Mistake with the version number?

### ISSUE THREAD

**Issue by hoechenberger** [wmvanvliet/mne-rsa#32]
Hello @wmvanvliet, the latest release is tagged as version 0.91 … I don't think this was intended, and you were planning to do 0.9.1 instead? If yes, … you may want to kill that tag and pull the package off of PyPI
Or simply make the next release a 1.0 :D

**Comment by wmvanvliet** [comment]
That was a mistake indeed. I've "yank"-ed the old version and put up 0.9.1 instead. Thanks for the heads up!

**Comment by hoechenberger** [comment]
I think we may need to do something about the conda-forge version, too

i can take a look tomorrow or so if you want!

**Comment by wmvanvliet** [comment]
if you could take a look, I'd be grateful. I don't know much about how conda-forge works.

**Comment by hoechenberger** [comment]
@wmvanvliet Done, see
https://github.com/conda-forge/admin-requests/pull/1003

cc @larsoner in case you're interested in the process
